### ISSUE TITLE
Unkown tag continue

### ISSUE THREAD

**Issue by kvz** [harrydeluxe/php-liquid#29]
It seems continue is not supported? Use case:

```
  {% for plan in site.data.public_plans %}
    {% if plan[1].slug == "sandbox" and showSandboxPlan == false %}
      {% continue %}
    {% endif %}
  {% endfor %}
```

**Comment by usamaejaz** [comment]
It will be good to have support for ```continue```

**Comment by NathanBaulch** [comment]
Implemented [here](https://github.com/NathanBaulch/php-liquid/commit/12db26ce358127be8cd469b80fc4e06bfaa7c4b6).

**Comment by kvz** [comment]
🎉
